"""Generated by valbridge - DO NOT EDIT
https://github.com/vectorfy-co/valbridge/docs
"""
from __future__ import annotations


from typing import Annotated, Any, Dict, TYPE_CHECKING

from annotated_types import Ge
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, TypeAdapter, model_validator

class UserCalendarGeo(BaseModel):
    lat: StrictFloat | None = None
    lng: StrictFloat | None = None


class UserCalendar(BaseModel):
    model_config = ConfigDict(extra='allow')
    category: StrictStr | None = None
    description: StrictStr | None = None
    duration: StrictStr | None = Field(default=None, description='Event duration')
    endDate: StrictStr | None = Field(default=None, description='Event ending time')
    geo: UserCalendarGeo | None = Field(default=None, description='Geographical location')
    location: StrictStr | None = None
    recurrenceDate: StrictStr | None = Field(default=None, description='Recurrence date')
    recurrenceDule: StrictStr | None = Field(default=None, description='Recurrence rule')
    startDate: StrictStr | None = Field(default=None, description='Event starting time')
    summary: StrictStr
    url: StrictStr | None = None

    @model_validator(mode='after')
    def _validate_advanced(self):
        # Advanced object validations
        # Validate required fields
        _all_props = self.model_dump(exclude_unset=True)
        if 'dtstart' not in _all_props:
            raise ValueError("Missing required property: 'dtstart'")
        return self

user_calendar = TypeAdapter(Annotated[UserCalendar, Field(description='A representation of an event')])

class UserUser(BaseModel):
    age: Annotated[StrictInt, Ge(0)] | None = None
    email: StrictStr
    id: StrictStr
    name: StrictStr | None = None

user_user = TypeAdapter(Annotated[UserUser, Field(description='A user object')])

schemas: Dict[str, Any] = {
    "user:Calendar": user_calendar,
    "user:User": user_user,
}

if TYPE_CHECKING:
    from typing import Protocol, TypedDict, overload
    from pydantic import TypeAdapter

    SchemaTypes = TypedDict('SchemaTypes', {
        "user:Calendar": type[Annotated[UserCalendar, Field(description='A representation of an event')]],
        "user:User": type[Annotated[UserUser, Field(description='A user object')]],
    }, total=False)

    class ValbridgeClient(Protocol):
        @overload
        def __call__(self, key: Literal["user:Calendar"]) -> TypeAdapter[Annotated[UserCalendar, Field(description='A representation of an event')]]: ...
        @overload
        def __call__(self, key: Literal["user:User"]) -> TypeAdapter[Annotated[UserUser, Field(description='A user object')]]: ...
        @overload
        def __call__(self, key: str) -> TypeAdapter[Any]: ...

