"""
Runtime client for valbridge-generated validators.

This module provides runtime schema lookup for validators generated by valbridge.
The client wraps a dictionary of validators and provides a callable interface.

Design decisions:

1. NAMESPACE:ID FORMAT - Keys use "namespace:id" format (e.g., "user:Profile")
   matching the Go CLI output. This provides:
   - Namespacing to avoid collisions when multiple config files define schemas
   - Clear provenance: namespace often maps to the config filename
   - Consistency across TypeScript and Python (same format in both)

2. NO DEFAULT NAMESPACE - Unlike the TypeScript client, Python doesn't support
   declaration merging for type safety on shorthand lookups. Without type
   benefits, shorthand adds API complexity without value. Full keys are clearer.

3. DICTIONARY-BASED STORAGE - Schemas stored in a dict keyed by "namespace:id".
   Generated code creates this dict statically. Runtime lookup is O(1).

4. CALLABLE INTERFACE - Client is callable: valbridge("namespace:id")
   This mimics function call semantics while allowing stateful configuration.

5. USER-FRIENDLY ERRORS - ValbridgeError includes "Run `valbridge generate`" hint
   because the most common error is forgetting to regenerate after schema changes.

Usage:
    from _valbridge import valbridge  # Generated by valbridge CLI

    User = valbridge("user:User")  # Returns Pydantic model class
    user = User.model_validate({"name": "Alice"})
"""

from typing import Any, Dict, Generic, Protocol, TypeVar

__all__ = ["ValbridgeClient", "ValbridgeError", "create_valbridge"]

T = TypeVar("T")
T_co = TypeVar("T_co", covariant=True)


class _SchemaLookup(Protocol[T_co]):
    def __call__(self, key: str) -> T_co: ...


class ValbridgeError(Exception):
    """
    Raised when a schema cannot be found.

    Includes a hint to run `valbridge generate` since the most common cause
    is forgetting to regenerate after adding/renaming schemas.
    """

    pass


class ValbridgeClient(Generic[T]):
    """
    Type-safe client for looking up schemas by namespace:id.

    Generic over T to allow typing the return value. In generated code,
    T is typically a Union of all generated model types, providing IDE
    autocompletion for the returned validator.

    The class wraps a dictionary but provides a callable interface for
    ergonomic usage: valbridge("namespace:id") instead of valbridge.get("namespace:id")
    """

    def __init__(self, schemas: Dict[str, T]) -> None:
        """
        Initialize the valbridge client.

        Args:
            schemas: Dictionary of schemas keyed by "namespace:id".
                     Keys use colon separator matching CLI output format.
        """
        self._schemas = schemas

    def __call__(self, key: str) -> T:
        """
        Look up a schema by key.

        Args:
            key: Schema key in "namespace:id" format (e.g., "user:Profile")
                 The namespace is typically the config filename without extension.
                 The id is the schema's declared identifier.

        Returns:
            The schema validator (e.g., Pydantic model class)

        Raises:
            ValbridgeError: If schema not found. Error message includes hint
                          to run `valbridge generate` since stale code is common.
        """
        if key not in self._schemas:
            msg = f"Unknown schema: {key}. Run `valbridge generate`."
            raise ValbridgeError(msg)

        return self._schemas[key]


def create_valbridge(schemas: Dict[str, T]) -> _SchemaLookup[T]:
    """
    Create an valbridge client for looking up schemas by namespace:id.

    This is the public factory function used by generated code. It returns
    a callable that provides runtime schema lookup.

    Why a factory function instead of direct ValbridgeClient instantiation?
    - Cleaner generated code: `valbridge = create_valbridge(schemas)`
    - Hides implementation detail (class vs function doesn't matter to user)
    - Allows future changes to internal representation without breaking API

    Args:
        schemas: Dictionary of schemas keyed by "namespace:id".
                 Generated code provides this dict with all validators.

    Returns:
        A ValbridgeClient instance. It's callable and takes a "namespace:id"
        key, returning the validator. Raises ValbridgeError if the key is not found.

    Example:
        >>> from valbridge import create_valbridge
        >>> schemas = {"user:Profile": ProfileModel, "config:TSConfig": TSConfigModel}
        >>> valbridge = create_valbridge(schemas)
        >>>
        >>> # Look up by full namespace:id key
        >>> Profile = valbridge("user:Profile")
        >>>
        >>> # Use the validator
        >>> user = Profile.model_validate({"name": "Alice"})
    """
    client = ValbridgeClient(schemas)
    return client
