"""valbridge Core - IR types and JSON Schema parser."""

from valbridge_core.diagnostics import Diagnostic, DiagnosticSeverity
from valbridge_core.ir import (
    AnyNode,
    ArrayConstraints,
    ArrayNode,
    BooleanNode,
    ConditionalNode,
    ContainsConstraint,
    DefaultBehavior,
    Dependency,
    EnumNode,
    FormatDetail,
    IntersectionNode,
    JsonValue,
    LiteralNode,
    NeverNode,
    NotNode,
    NullNode,
    NullableNode,
    NumberConstraints,
    NumberNode,
    ObjectNode,
    OneOfNode,
    PatternPropertyDef,
    PropertyDef,
    PropertyDependency,
    RefNode,
    AliasInfo,
    CodeStub,
    SchemaAnnotations,
    SchemaNode,
    SchemaDependency,
    StringConstraints,
    StringNode,
    Transform,
    TupleNode,
    TypeGuard,
    TypeGuardedNode,
    UnionNode,
)
from valbridge_core.parser import parse, parse_enriched

__all__ = [
    # Parser
    "parse",
    "parse_enriched",
    # Diagnostics
    "Diagnostic",
    "DiagnosticSeverity",
    # Schema nodes
    "SchemaNode",
    "Transform",
    "AliasInfo",
    "CodeStub",
    "DefaultBehavior",
    "FormatDetail",
    "StringNode",
    "NumberNode",
    "BooleanNode",
    "NullNode",
    "LiteralNode",
    "EnumNode",
    "ArrayNode",
    "TupleNode",
    "ObjectNode",
    "UnionNode",
    "OneOfNode",
    "IntersectionNode",
    "NotNode",
    "ConditionalNode",
    "TypeGuardedNode",
    "NullableNode",
    "RefNode",
    "AnyNode",
    "NeverNode",
    "SchemaAnnotations",
    # Constraint types
    "StringConstraints",
    "NumberConstraints",
    "ArrayConstraints",
    "ContainsConstraint",
    "PropertyDef",
    "PatternPropertyDef",
    "Dependency",
    "PropertyDependency",
    "SchemaDependency",
    "TypeGuard",
    # Value types
    "JsonValue",
]
